### ISSUE TITLE
As a manager, I want the S3-browser to be deployable and accessible from a '/some_path' URL

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/s3-browser-cloudfront#68]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

Engineering Node system administration and overall path organization.

### 💪 Motivation

...so that I can the s3-browser can share a domain name with other applications, e.g.

- main web site: https://pds.nasa.gov
- api: https://pds.nasa.gov/api
- s3-browser: https://pds.nasa.gov/data

### 📖 Additional Details

Currently, the application only works if accessible from `/` for example `https://data.pds.nasa.gov`
We would like  to make the application work from a deployment like https://dwfmsppt3a750.cloudfront.net/data/ (in Dev)

### Acceptance Criteria

**Given** 
**When I perform** 
**Then I expect**

**Comment by eddiesarevalo** [comment]
@anilnatha @tloubrieu-jpl 
I added an environment variable to the webpack config so that the string matching will be what is set. For example here:
<img width="848" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0dyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f58837e75a4f8fca1e2b214c2a8634757e5e733d/Screenshot%202024-07-02%20at%203.29.14%E2%80%AFPM.png" alt="Screenshot 2024-07-02 at 3.29.14 PM.png" />

It will get it from the webpack config
<img width="490" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0tyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e94febbda34675a45d85f90d384daead4add9c6e/Screenshot%202024-07-02%20at%203.30.56%E2%80%AFPM.png" alt="Screenshot 2024-07-02 at 3.30.56 PM.png" />

So in the built code it looks like `"/data/"==location.pathname`

The problem now is the url itself. For example https://dwfmsppt3a750.cloudfront.net/data/catalina-sky-survey/
Going to this url will attempt to open that location so the javascript will never run. Static website host used to cover this part but now we need a new solution. We could set a cloudfront function to reroute anything /data/* to /data/
or maybe we can do what @anilnatha mentioned and make some sort of proxy.

**Comment by jordanpadams** [comment]
Status: @eddiesarevalo is blocked by cloudfront function. code should be updated and ready for this.

**Comment by tloubrieu-jpl** [comment]
That works perfectly on our MCP Dev account.

**Comment by jordanpadams** [comment]
Skipping I&T. Tested via inspection during website deployment
